### PR TITLE
Update branch of OpenSearch from 1.x to 1.1 

### LINKED ISSUE #64: [BUG] Main changes need to be backported into 1.1
**Describe the bug**
Bundle builds fail for 1.1 because changes for snapshots have not been back-ported, addition changes might be required please update 1.1 to whatever changes it should have for the 1.1 release.

### PR DESCRIPTION
**Pull request by aditjind**
### Description
Update branch of OpenSearch from 1.x to 1.1 
 
### Issues Resolved
#64

PR (opensearch-project/common-utils#65) with all the commits cherry picked from the main branch. We can keep this PR as an artifact.

Issue in the Build Repository: https://github.com/opensearch-project/opensearch-build/issues/410
Prequel to this PR (https://github.com/opensearch-project/common-utils/pull/67)

After this PR is merged. This [PR](https://github.com/opensearch-project/opensearch-build/pull/430) needs to be reviewed and merged. 
 
### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [X] New functionality has been documented.
  - [X] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by aditjind** [comment]
Just checked OpenSearch doesn't have a 1.1 branch. Marking this PR as a draft (Pending further discussion).

**Comment by aditjind** [comment]
@peternied @dblock We need this one merged too, but we are blocked on https://github.com/opensearch-project/opensearch-build/pull/430

**Comment by dblock** [comment]
OpenSearch is working in 1.x for 1.1 rn to minimize backports, so leave it as is until that becomes 1.1.

With maven this annoyance goes away, so this is the last release we're doing this.

**Comment by dblock** [comment]
I also merged https://github.com/opensearch-project/opensearch-build/pull/430 after fixing #69

**Comment by dblock** [comment]
Did this in https://github.com/opensearch-project/common-utils/pull/79/files

**Pull request closed without merging**
