### PR TITLE
Add missing ctx variables

### PR DESCRIPTION
**Pull request by partlov**
Signed-off-by: Petar Partlov <partlov@gmail.com>

### Description
Added missing fields to ctx so content is aligned with documentation and our plans.
 
### Issues Resolved
- opensearch-project/alerting#200
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by lezzago** [comment]
We need to rebase. If the external contributor can't update this, someone from the Alerting team will take it

**Comment by partlov** [comment]
> We need to rebase. If the external contributor can't update this, someone from the Alerting team will take it

Rebased

**Comment by riysaxen-amzn** [comment]
@partlov  can we resolve the conflicts

**Comment by dblock** [comment]
@riysaxen-amzn Looks like a very old PR, make you can help rebase it and get it merged?

**Comment by dblock** [comment]
Closing as unfinished, please feel free to finish and reopen. Thanks!

[Catch All Triage w/ [1](https://github.com/dblock), [2](https://github.com/krisfreedain), [3](https://github.com/andrross)]

**Pull request closed without merging**
