### PR TITLE
Version changed to rc1

### PR DESCRIPTION
**Pull request by skkosuri-amzn**
### Description
Rename artifacts version to rc1.
 
### Issues Resolved
Rename artifacts version to rc1.
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by aditjind — APPROVED** [review]

**Comment by bowenlan-amzn** [comment]
leave a note, some point we need to update the workflow file to the new version also

**Comment by dblock** [comment]
Don't we need to do this all at the same time, starting with OpenSearch? Otherwise this change breaks all plugins that depend on it?

**Review by dblock — APPROVED** [review]
I'll hit approve cause by itself the change is fine, but see my comment.

**Comment by dblock** [comment]
Will you also change beta1 to rc1 in https://github.com/opensearch-project/common-utils/blob/main/.github/workflows/ci.yml? It doesn't really matter for the build which identifiers are used, but this way we know we're there.

**Pull request merged**
