### PR TITLE
Addressing 'org.apache.hc.core5.http.ParseException: Invalid protocol version' under JDK 16+

### PR DESCRIPTION
**Pull request by reta**
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

### Description
When using JDK 16+, the `org.apache.hc.core5.http.ParseException: Invalid protocol version` is being thrown.
 
### Issues Resolved
See please https://issues.apache.org/jira/browse/HTTPCLIENT-2219
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@dblock could you please check this one out?

**Comment by dblock** [comment]
Why didn't CI run here?

**Comment by reta** [comment]
> Sorry for the delay, just noticing this. Why didn't CI run here?

Hm .. not sure to be fair

**Comment by dblock** [comment]
I have admin rights on the org and yet I don't see any approval button ... let me force push something here.

**Comment by dblock** [comment]
Looks like CI kicked in now 🤷

**Review by dblock — APPROVED** [review]

**Comment by reta** [comment]
> Looks like CI kicked in now 🤷

Thanks a lot @dblock !

**Review by lezzago — APPROVED** [review]

**Pull request merged**
