### PR TITLE
Make 1.1 branch at par with the main branch

### PR DESCRIPTION
**Pull request by aditjind**
### Description
Merges commits from the main branch to the 1.1 branch. 
 
### Issues Resolved
https://github.com/opensearch-project/common-utils/issues/64

Build Suceeded

 
### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [X] New functionality has been documented.
  - [X] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by aditjind** [comment]
Marking this as a Draft PR as per offline conversation with @skkosuri-amzn

**Review by skkosuri-amzn — APPROVED** [review]

**Comment by skkosuri-amzn** [comment]
@akbhatta Could you pls review approve this merge from `main` to `1.x` and `1.1`.

**Comment by peternied** [comment]
Cannot approve with merge conflicts, but I can verify that https://github.com/opensearch-project/common-utils/pull/57 and https://github.com/opensearch-project/common-utils/pull/58 were merged which AFAIK are all that is required to fix the snapshot issues.

**Comment by dblock** [comment]
> Cannot approve with merge conflicts, but I can verify that #57 and #58 were merged which AFAIK are all that is required to fix the snapshot issues.

We do want all changes from main in 1.1 I believe.

**Comment by skkosuri-amzn** [comment]
We pulled only the build related changes from `main`. Notifications related changes are not pulled from `main` as that feature is not planned for `1.1` release. I see @aditjind merged #67 . We are good i guess,  anything missing?

**Comment by dblock** [comment]
> We pulled only the build related changes from `main`. Notifications related changes are not pulled from `main` as that feature is not planned for `1.1` release. I see @aditjind merged #67 . We are good i guess, anything missing?

Got it. Thanks.

**Comment by dblock** [comment]
So should this be closed without merging?

**Comment by skkosuri-amzn** [comment]
> So should this be closed without merging?

Yes. @aditjind could you please close this.

**Pull request closed without merging**
