### PR TITLE
common utils to support Microsoft teams in notifications

### PR DESCRIPTION
**Pull request by zhichao-aws**
### Description
Add common utils to support Microsoft teams in notifications plugin
 
### Issues Resolved
https://github.com/opensearch-project/notifications/issues/585

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by zhichao-aws** [comment]
PR in notifications: https://github.com/opensearch-project/notifications/pull/676

**Comment by zhichao-aws** [comment]
Please add backport 2.x label, I don't have permission

**Comment by zhichao-aws** [comment]
Is the codecov target 75% for this whole project or for this PR? Do I need to further increase the coverage?
https://github.com/opensearch-project/common-utils/pull/428/checks?check_run_id=13480804992

**Comment by zhichao-aws** [comment]
Hi team, please help review and add backport 2.x label.

**Review by Hailong-am — APPROVED** [review]

**Comment by zhichao-aws** [comment]
@opensearch-project/common-utils Could someone help review this PR? Thanks!

**Comment by zhichao-aws** [comment]
Hi @lezzago @qreshi @AWSHurneyt , you contributed many codes to the notifications plugin and are familiar with it. Could you please take a look and help review this PR? Thanks!

**Comment by lezzago** [comment]
@zhichao-aws has this been tested locally with the Notification plugin to ensure the new channel works?

**Comment by zhichao-aws** [comment]
@lezzago Yes, we test the function locally and here are some screenshots:
 
image
image
image

**Review by lezzago — APPROVED** [review]

**Review by AWSHurneyt — APPROVED** [review]

**Comment by Hailong-am** [comment]
@AWSHurneyt @lezzago could you help to merge it and add backport 2.x label?

**Pull request merged**
